version: '3'
services:
  hc-mysql:
    container_name: hc-mysql
    image: mysql:5.7.20
    ports:
      - 5306:3306
    volumes:
      - ./mountd/mysql/var/lib/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_USER=dbuser
      - MYSQL_PASSWORD=password
  hc-memcached:
    container_name: hc-memcached
    image: memcached:1.5.2
    ports:
      - 31211:11211
  hc-redis:
    container_name: hc-redis
    image: redis:4.0.2
    ports:
      - 8379:6379
    volumes:
      - ./mountd/redis/data:/data
networks:
  default:
    external:
      name: kawaii-bot
